package commands.enums;

public enum CommandType {

    CREATEUSER,
    CREATETASK,
    SHOWALLUSERS,
    CHANGETASKSTATUS,
    CHANGETASKTITLE,
    CHANGETASKDESCRIPTION,
    CHANGETASKDUEDATE,
    LISTALLTASKS,
    LISTALLTASKSBYSTATUS,
    REMOVETASK,
}
